project:
  type: website
  output-dir: docs
  
execute:
  freeze: auto  # re-render only when source changes
  
website:
  title: "Statistics for Psychologists"
  favicon: "Images/favicon.png"
  page-navigation: true
  back-to-top-navigation: true
    
  repo-url: https://github.com/M1V0/FASS512
  repo-actions: [edit, issue]
  
  navbar:
    #logo: "Images/icon.png"
    left:
      #- text: Home
      #  file: index.qmd
      - text: Week 1
        file: Week11.qmd
      #- text: Week 2
      #  file: Worksheets/Worksheet_wk2.qmd

  sidebar:
  
    collapse-level: 1
    style: "floating"
    
    contents: /*

#     - section: "PSYC214"
#       contents: PSYC214/*
#       
#     - section: "PSYC234"
#       contents: PSYC234/*
#       
#     - section: "PSYC401"
#       contents: PSYC401/*
#       
#     - section: "PSYC402"
#       contents: PSYC402/* 
        
        
  page-footer:
    left: "Website developed by Matthew Ivory"
    right:       
      - icon: github
        href: https://github.com/mg78/2324_PSYC402

format:
  html:
    theme: 
      - default
      - custom.scss
    #css: styles.css
    code-overflow: wrap
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
    toc: true
    include-in-header:
      - text: |
          <script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
          <script language="JavaScript" type="text/javascript" src="/function.js"></script>
      

editor: source

validate-yaml: false
